const USER_TABLE = `
CREATE TABLE IF NOT EXISTS Users (
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    creation_Date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status BOOLEAN DEFAULT true,
    email VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);
`;

const Posts_TABLE = `
CREATE TABLE IF NOT EXISTS Posts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT NOT NULL,
    Content TEXT NOT NULL,
    Creation_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES Users(id)
    ON DELETE CASCADE
);
`;

const Comments_TABLE = `
CREATE TABLE IF NOT EXISTS Comments (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT NOT NULL,
    Post_ID INT NOT NULL,
    Content TEXT NOT NULL,
    Creation_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES Users(ID)
    ON DELETE CASCADE,
    FOREIGN KEY (Post_ID) REFERENCES Posts(ID)
    ON DELETE CASCADE
);
`;

const Votes_TABLE = `
CREATE TABLE IF NOT EXISTS Votes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Post_ID INT NOT NULL,
    User_ID INT NOT NULL,
    Is_Positive BOOLEAN NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Post_ID) REFERENCES Posts(ID)
    ON DELETE CASCADE,
    FOREIGN KEY (User_ID) REFERENCES Users(ID)
    ON DELETE CASCADE,
    UNIQUE (Post_ID, User_ID) 
);
`;

export { USER_TABLE, Posts_TABLE, Comments_TABLE, Votes_TABLE };
