version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - m223_project_mariadb:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret123
      - MYSQL_DATABASE=minitwitter
      - MYSQL_USER=minitwitter
      - MYSQL_PASSWORD=supersecret123
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=supersecret123
    ports:
      - "9200:80"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    environment:
      - DB_NAME=minitwitter
      - DB_HOST=mariadb
      - DB_USER=minitwitter
      - DB_PASSWORD=supersecret123
    command: ["bun", "run", "index.ts"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:3000
    command: ["bun", "run", "dev", "--host"]

volumes:
  m223_project_mariadb:
