FROM node:18-alpine

RUN apk add --no-cache curl bash

RUN curl -fsSL https://bun.sh/install | bash

ENV PATH="/root/.bun/bin:$PATH"

WORKDIR /app

COPY package.json bun.lockb tsconfig.json ./

RUN bun install

COPY . .

EXPOSE 3000

CMD ["bun", "run", "index.ts"]
