# Usa la imagen oficial de Bun
FROM oven/bun:latest

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de configuración
COPY server/package.json server/bun.lockb ./

# Instala las dependencias usando Bun
RUN bun install

# Copia el resto del código de la aplicación
COPY server/ .

# Exponer el puerto en el que correrá el backend
EXPOSE 3000

# Establecer el entrypoint a bun
ENTRYPOINT ["bun"]

# Comando para iniciar el backend
CMD ["index.ts"]
